version: '3.7'

services:
  app:
    image: userhub-bd-backend:latest
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: userhub-bd-backend
    # Roda o container na rede padrão do Docker, em vez de criar uma nova
    network_mode: bridge
    ports:
      - ${PORT_BACKEND}:${PORT_BACKEND}
    restart: always
    env_file: .env